### ISSUE TITLE
QOTD system

### ISSUE THREAD

**Issue by srnyx** [Venox-Network/cobalt#1]
- Questions are added via `/qotd question:<question>` and only addable by `@Owner` and `@QOTD Manager `
     - Duplicate questions will not be added and will throw a warning (punctuation will be ignored when checking for duplicates)
- Questions are automatically sent at 5 PM EST every day in all channels called `#qotd`
     - It will go through the list of questions, once it reaches the end (it will check *after* it has sent each QOTD so that it always sends one) it will ping `@everyone` in `#qotd-manager-chat` notifying them that the bot has run out of questions. If there are still no more questions available the next day, it will reuse the oldest questions.
     - Each question will have an ID (ex: 1, 2, 3, 4) so it can be identified, IDs are assigned based on when the question was added
     - A thread will be made for each question titled `Question #`, # being the question's ID (or could be the date).
- Question list with `/qotd list` that has buttons to turn pages (like Dank Memer's help command)

**Either the bot will send a message in #qotd, create a thread here, then publish it, then create a thread in all the servers it's in in their `#qotd` channels. Or, the bot will send the QOTD to each individual server, create the thread, then publish it if possible.**

**Could make use of https://github.com/srnyx/venox/issues/2**

**Comment by DWAA1660** [comment]
Will modals be ok

**Comment by srnyx** [comment]
> Will modals be ok

Modal for what part?
