### ISSUE TITLE
Reaction / poll system

### ISSUE THREAD

**Issue by srnyx** [Venox-Network/cobalt#15]
The bot will add reactions of every emoji present in the message (dynamic) or add set emojis/reactions specified in the command (set).
It can be done once (non-continuous), once using set emojis (non-continuous set), toggled per channel (continuous), or toggled per channel using set emojis (continuous set).

**Commands:**
- Non-continuous dynamic:
`/react message_id:<message id>`
If possible, the command could also work by just replying to the message and running `/react` (and Apps).
- Non-continuous set:
`/react message_id:<message id> emojis:<list of emojis, ignores other characters>`
Same as non-continuous except it will use set emojis instead of all of the emojis inside of the message.
- Continuous dynamic:
`/react channel:<#channel>`
This will listen to all messages sent in the channel and automatically do what non-continuous does.
- Continuous set:
`/react channel:<#channel> emojis:<list of emojis, ignores other characters>`
This is the same as continuous except it will only add the specified emojis (example: `#daily-wisdom` in CommandGeek Labs).

**Comment by DWAA1660** [comment]
@srnyx is this done?

**Comment by srnyx** [comment]
> @srnyx is this done?

No, you've only implemented 1/4 of the things I listed
