### ISSUE TITLE
Automatic thread creator

### ISSUE THREAD

**Issue by srnyx** [Venox-Network/cobalt#2]
A channel can be set using a slash command that will make it so that every time someone sends a message in the channel, a thread will be created for that message.

### Commands
`/autothread channel:[channel] name:[name of each thread] ignore:[phrases that won't create a thread]`

### Variables (for `name`)
`%message%` - as many characters possible from the beginning of the message that activated the automation. If too long, the last 3 characters should be `...`
`%channel%` - the name of the channel the thread is created in. Would update accordingly if the channel is renamed
`%id%` - a number that is assigned to each thread, basically like Carl-bot suggestions, increments by 1 for each thread

### Command example
`/autothread channel:#suggestions name:{channel} {id} ignore:Hello!`
This would automatically create threads for each message sent. The first thread would be named `suggestions 1`, the second will be named `suggestions 2`, and so on. However, if one of these messages contains `Hello!` in it, the thread will not be created.

### Default values (if not specified, it will use these)
`channel` - the channel the command was executed in
`name` - `%message%`
`ignore` - empty

**Could be used for https://github.com/srnyx/venox/issues/1**

**Comment by Chrizxz** [comment]
do `/autothread off`

**Comment by Chrizxz** [comment]
do a `/autothread channel_id off` so that we don't have to add an extra command to turn it off like `/unautothread`

**Comment by srnyx** [comment]
> do a `/autothread channel_id off` so that we don't have to add an extra command to turn it off like `/unautothread`

Added to main description as `toggle:<on|off>`

**Comment by srnyx** [comment]
Not everything here is done

**Comment by srnyx** [comment]
Everything except `name` and `ignore` is done
*May separate `ignore` into its own sub-command to allow for more complex parameters (roles, message content, users, etc...)*

**Comment by srnyx** [comment]
`name` is done, just need to do `ignore` now
