### ISSUE TITLE
Mute role and server mute connection

### ISSUE THREAD

**Issue by srnyx** [Venox-Network/cobalt#33]
Check if the user has the mute role whenever they join a VC, and if they do, server-mute them. If they don't (and were previously server muted by the bot, not by a user), unserver-mute them. Since it should only unserver-mute if they were previously muted by the BOT, then a list of users will probably have to be stored.

**Comment by skandabhairava** [comment]
Hows this supposed to work?? Doesnt "timeout" already disable VCs??

**Comment by srnyx** [comment]
> Hows this supposed to work?? Doesnt "timeout" already disable VCs??

Some servers are still using legacy mute systems (basically all Venox servers). I basically just want the bot to check if the user has the mute role whenever they join a VC, and if they do, server mute them. If they don't and were previously server muted (by the bot, not by a user. This may have to be stored in a list of users that were server muted by the bot for having the mute role) then the bot will un server mute them.
