### ISSUE TITLE
Auto-message deleter

### ISSUE THREAD

**Issue by srnyx** [Venox-Network/cobalt#34]
A command that will make it so the bot will automatically delete any **new** messages sent in a channel.
`/autodelete channel:<text channel> bypass:<role>`
`channel`: the channel in which it will auto-delete new messages sent
`bypass`: Role that will not have their messages deleted

**Comment by Chrizxz** [comment]
why

**Comment by srnyx** [comment]
> why

For things like thread-only channels where we want to have an info message
