### ISSUE TITLE
JavaScript commands to Python

### ISSUE THREAD

**Issue by srnyx** [Venox-Network/cobalt#37]
Convert existing JavaScript (`master`) commands to Python (`python`)

**Comment by DWAA1660** [comment]
why you assign chriz and not me

**Comment by srnyx** [comment]
> why you assign chriz and not me

It only lets me assign collaborators

**Comment by DWAA1660** [comment]
all commands are switched over (i think)

**Comment by Chrizxz** [comment]
> all commands are switched over (i think)
ok

**Comment by srnyx** [comment]
> all commands are switched over (i think)

Activities

**Comment by Chrizxz** [comment]
> all commands are switched over (i think)
> 
>> Activities

Decided it wasn't really needed due to discord's new activities in servers

**Comment by srnyx** [comment]
`/help` and `/eval` have not been added yet
