### ISSUE TITLE
`/superkick`

### ISSUE THREAD

**Issue by Chrizxz** [Venox-Network/cobalt#49]
### General description

Literally `/superban` but it kicks instead of bans. Any user kicked with this command will be kicked in every server the bot is in (basically all Venox Network servers)

### Steps to accomplish

`/superkick user:<user ID> reason:<reason>`

### Media

![Discord_qaNRGknAQt](https://user-images.githubusercontent.com/55815776/167507111-3cc339ce-ca06-47d7-b58f-7007d30cb0cf.png)
*Image depicts the current `/superban` command, `/superkick` will have the same parameters, though.*

### Additional information

- [x] Confirmation embed with yes/no buttons:
```
Are you sure you want to **superkick** this user?
This will kick them from **all** Venox Network servers!
[Yes] [No]
```

**Comment by srnyx** [comment]
Not everything is done with this

**Comment by srnyx** [comment]
Done except confirmation embed
