### ISSUE TITLE
Very badly made code for venox (python)

### ISSUE THREAD

**Issue by Anthony2be** [Venox-Network/cobalt#51]
### General description

some actually good code and not spaghetti

### Steps to accomplish

redesign code, follow the actual python guidelines, and use common sense

### Media

![image](https://user-images.githubusercontent.com/50805238/167518807-18fa5411-5ef3-499b-b458-42a08ea7b0ff.png)
![image](https://user-images.githubusercontent.com/50805238/167518810-048258b8-8ee4-492f-b1ba-7f939cc59cf7.png)

**Comment by srnyx** [comment]
Can't just say the code is bad without giving any insight as to why.
If you noticed it says `soontobeconfig.txt` meaning it's not final and just temporary.

**Comment by Anthony2be** [comment]
> Can't just say the code is bad without giving any insight as to why. If you noticed it says `soontobeconfig.txt` meaning it's not final and just temporary.

i literally showed pictures of *some* of the bad code

examples:
opens same file like 5 times
uses txt for storing data instead of smth like json, yaml, or dotenv

**Comment by srnyx** [comment]
> > Can't just say the code is bad without giving any insight as to why. If you noticed it says `soontobeconfig.txt` meaning it's not final and just temporary.
> 
> i literally showed pictures of _some_ of the bad code
> 
> examples: opens same file like 5 times uses txt for storing data instead of smth like json, yaml, or dotenv

> If you noticed it says `soontobeconfig.txt` meaning it's not final and just temporary.

**Comment by Anthony2be** [comment]
> > > Can't just say the code is bad without giving any insight as to why. If you noticed it says `soontobeconfig.txt` meaning it's not final and just temporary.
> > 
> > 
> > i literally showed pictures of _some_ of the bad code
> > examples: opens same file like 5 times uses txt for storing data instead of smth like json, yaml, or dotenv
> 
> > If you noticed it says `soontobeconfig.txt` meaning it's not final and just temporary.

i just talked with dwaa and he doesn't plan on changing it and the fact that he opens the same file like 5 times has nothing to do with the name of the file

plus he firt got all the lines in the file then narrows it down instead of getting the specific line

**Comment by DWAA1660** [comment]
> > > > Can't just say the code is bad without giving any insight as to why. If you noticed it says `soontobeconfig.txt` meaning it's not final and just temporary.
> > > 
> > > 
> > > i literally showed pictures of _some_ of the bad code
> > > examples: opens same file like 5 times uses txt for storing data instead of smth like json, yaml, or dotenv
> > 
> > 
> > > If you noticed it says `soontobeconfig.txt` meaning it's not final and just temporary.
> 
> i just talked with dwaa and he doesn't plan on changing it and the fact that he opens the same file like 5 times has nothing to do with the name of the file
> 
> plus he first got all the lines in the file then narrows it down instead of getting the specific line

I didn't say I didn't plan on changing it I just didn't know how and we needed to have config before we released

**Comment by Anthony2be** [comment]
> > i just talked with dwaa and he doesn't plan on changing it and the fact that he opens the same file like 5 times has nothing to do with the name of the file
> > plus he first got all the lines in the file then narrows it down instead of getting the specific line
> 
> I didn't say I didn't plan on changing it I just didn't know how and we needed to have config before we released

well guess its your lucky day since I'll have to spend the next like 2 hours refactoring all the code to make it somehow understandable
