### ISSUE TITLE
Voice channel roles

### ISSUE THREAD

**Issue by srnyx** [Venox-Network/cobalt#53]
When a user joins a specific voice channel, they get a role. The role is removed when they leave the channel.

`/vcrole channel:<vc> role:<@role>`

**Comment by DWAA1660** [comment]
Is this so only people in vc can see certain channels or do I misunderstand

**Comment by srnyx** [comment]
> Is this so only people in vc can see certain channels or do I misunderstand

Yes, like only people in General VC can see `#voice-and-music` and only people in Events VC can see `#event-chat`

**Comment by srnyx** [comment]
Not sure how needed this is anymore now that there are voice text channels
