### ISSUE TITLE
Translate context menu

### ISSUE THREAD

**Issue by DWAA1660** [Venox-Network/cobalt#55]
Make so you can right-click a message and use an App to translate a message to English

![image](https://user-images.githubusercontent.com/80738438/168497420-71826416-fa53-4f81-9223-916dd5a8dfa3.png)

**Comment by srnyx** [comment]
Afraid this may be too inaccurate and inconvenient (imagine having to constantly translating messages when people are having a conversation in a different language).

**Comment by DWAA1660** [comment]
> Afraid this may be too inaccurate and inconvenient (imagine having to constantly translating messages when people are having a conversation in a different language).

i think the accuracy will be pretty good idk about the inconvienece
