### ISSUE TITLE
Rename everything to `Cobalt`

### ISSUE THREAD

**Issue by srnyx** [Venox-Network/cobalt#61]
Change all `Venox` instances (referring to the bot, not the network) and change them to `Cobalt`

**Comment by DWAA1660** [comment]
the only venox is venox.py im pretty sure

**Comment by srnyx** [comment]
> the only venox is venox.py im pretty sure

![](https://img.srnyx.xyz/r/idea64_CzgzPABmcO.png)

**Comment by DWAA1660** [comment]
> > the only venox is venox.py im pretty sure
> 
> ![](https://camo.githubusercontent.com/75e8ad835b9f99bb0ef55a0ea4643277d496d6bf4d2f8c724e6a3c1b07fa9c5f/68747470733a2f2f696d672e73726e79782e78797a2f722f6964656136345f437a677a5041426d634f2e706e67)

Those are all referring to the network except maybe db

**Comment by srnyx** [comment]
> Those are all referring to the network except maybe db

No they aren't. "Venox moderates in", it would've said "Venox Network"
