### ISSUE TITLE
One-message channels

### ISSUE THREAD

**Issue by srnyx** [Venox-Network/cobalt#63]
A way to set channels that users can only send one (or more, configurable per-channel) message in. Maybe create a role called "Sent messages" and then add it to channel overrides so that the role can't send messages. Then, when someone has sent all of their messages, it gives them the role.

**Command:** `/onemessage channel:<#text channel> messages:<#>`

`messages` = how many messages each person can send (can be 1 or more)

**Comment by skandabhairava** [comment]
A small idea, instead of saving user id in the Database, we can check the history of the channel, and check the amount of msgs a user can send, if the limit is exceeded, we can edit the channel, for the user's "Send Message" permission as False.

**Comment by srnyx** [comment]
> A small idea, instead of saving user id in the Database, we can check the history of the channel, and check the amount of msgs a user can send, if the limit is exceeded, we can edit the channel, for the user's "Send Message" permission as False.

It might take a really long time to search through all of the messages in the channel depending on how many there are.
Permissions would get too messy, especially with 100+ people. A role would be much nicer to use as well since we can easily remove it to allow the user to resend their messages if they want or something.
